DROP SCHEMA IF EXISTS staging_l1 CASCADE;

DROP SCHEMA IF EXISTS staging_l2 CASCADE;

DROP SCHEMA IF EXISTS rdv CASCADE;

DROP SCHEMA IF EXISTS bdv CASCADE;

DROP SCHEMA IF EXISTS star CASCADE;

DROP SCHEMA IF EXISTS meta CASCADE;

DROP SCHEMA IF EXISTS metrics CASCADE;

DROP SCHEMA IF EXISTS error CASCADE;
