CREATE SCHEMA IF NOT EXISTS staging_l1;

CREATE SCHEMA IF NOT EXISTS staging_l2;

CREATE SCHEMA IF NOT EXISTS rdv;

CREATE SCHEMA IF NOT EXISTS bdv;

CREATE SCHEMA IF NOT EXISTS star;

CREATE SCHEMA IF NOT EXISTS meta;

CREATE SCHEMA IF NOT EXISTS metrics;

CREATE SCHEMA IF NOT EXISTS error;
