SELECT 'Step 1' as step, 'northwind.categories' as tbl, count(*) as cnt FROM northwind.categories UNION ALL
SELECT 'Step 1' as step, 'northwind.customers' as tbl, count(*) as cnt FROM northwind.customers UNION ALL
SELECT 'Step 1' as step, 'northwind.employee_territories' as tbl, count(*) as cnt FROM northwind.employee_territories UNION ALL
SELECT 'Step 1' as step, 'northwind.employees' as tbl, count(*) as cnt FROM northwind.employees UNION ALL
SELECT 'Step 1' as step, 'northwind.order_details' as tbl, count(*) as cnt FROM northwind.order_details UNION ALL
SELECT 'Step 1' as step, 'northwind.orders' as tbl, count(*) as cnt FROM northwind.orders UNION ALL
SELECT 'Step 1' as step, 'northwind.products' as tbl, count(*) as cnt FROM northwind.products UNION ALL
SELECT 'Step 1' as step, 'northwind.region' as tbl, count(*) as cnt FROM northwind.region UNION ALL
SELECT 'Step 1' as step, 'northwind.shippers' as tbl, count(*) as cnt FROM northwind.shippers UNION ALL
SELECT 'Step 1' as step, 'northwind.suppliers' as tbl, count(*) as cnt FROM northwind.suppliers UNION ALL
SELECT 'Step 1' as step, 'northwind.territories' as tbl, count(*) as cnt FROM northwind.territories UNION ALL
SELECT 'Step 1' as step, 'northwind.us_states' as tbl, count(*) as cnt FROM northwind.us_states UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_categories' as tbl, count(*) as cnt FROM staging_l1.l1_categories UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_customers' as tbl, count(*) as cnt FROM staging_l1.l1_customers UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_employee_territories' as tbl, count(*) as cnt FROM staging_l1.l1_employee_territories UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_employees' as tbl, count(*) as cnt FROM staging_l1.l1_employees UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_order_details' as tbl, count(*) as cnt FROM staging_l1.l1_order_details UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_orders' as tbl, count(*) as cnt FROM staging_l1.l1_orders UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_products' as tbl, count(*) as cnt FROM staging_l1.l1_products UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_region' as tbl, count(*) as cnt FROM staging_l1.l1_region UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_shippers' as tbl, count(*) as cnt FROM staging_l1.l1_shippers UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_suppliers' as tbl, count(*) as cnt FROM staging_l1.l1_suppliers UNION ALL
SELECT 'Step 2' as step, 'staging_l1.l1_territories' as tbl, count(*) as cnt FROM staging_l1.l1_territories UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_categories' as tbl, count(*) as cnt FROM staging_l2.l2_categories UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_customers' as tbl, count(*) as cnt FROM staging_l2.l2_customers UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_employee_territories' as tbl, count(*) as cnt FROM staging_l2.l2_employee_territories UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_employees' as tbl, count(*) as cnt FROM staging_l2.l2_employees UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_order_details' as tbl, count(*) as cnt FROM staging_l2.l2_order_details UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_orders' as tbl, count(*) as cnt FROM staging_l2.l2_orders UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_products' as tbl, count(*) as cnt FROM staging_l2.l2_products UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_region' as tbl, count(*) as cnt FROM staging_l2.l2_region UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_shippers' as tbl, count(*) as cnt FROM staging_l2.l2_shippers UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_suppliers' as tbl, count(*) as cnt FROM staging_l2.l2_suppliers UNION ALL
SELECT 'Step 3' as step, 'staging_l2.l2_territories' as tbl, count(*) as cnt FROM staging_l2.l2_territories 
